from pathlib import Path
from datetime import datetime


def save_html_report(scan_result):

    # Create reports folder
    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)

    # Timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Filename
    filename = (
        scan_result["target"].replace(".", "_")
        + "_"
        + timestamp
        + ".html"
    )

    report_path = reports_dir / filename

    # ------------------------------------------
    # Build Ports Table
    # ------------------------------------------

    ports_rows = ""

    for port in scan_result["ports"]:

        banner = port.get("banner") or "No banner"

        banner = banner.splitlines()[0]

        ports_rows += f"""
        <tr>
            <td>{port['port']}</td>
            <td>{port['service']}</td>
            <td>{banner}</td>
        </tr>
        """

    # ------------------------------------------
    # SSL Section
    # ------------------------------------------

    ssl_section = ""

    ssl = scan_result.get("ssl")

    if ssl:

        ssl_section = f"""
        <h2>SSL Certificate</h2>

        <table>

            <tr>
                <td>Status</td>
                <td>{ssl['status']}</td>
            </tr>

            <tr>
                <td>Issuer</td>
                <td>{ssl['issuer']}</td>
            </tr>

            <tr>
                <td>Days Remaining</td>
                <td>{ssl['days_remaining']}</td>
            </tr>

        </table>
        """

    # ------------------------------------------
    # Header Section
    # ------------------------------------------

    header_section = ""

    headers = scan_result.get("headers")

    if headers:

        rows = ""

        for header, info in headers["headers"].items():

            status = "✅ Present" if info["present"] else "❌ Missing"

            rows += f"""
            <tr>
                <td>{header}</td>
                <td>{status}</td>
            </tr>
            """

        percentage = (headers["score"] / headers["total"]) * 100

        header_section = f"""
        <h2>HTTP Security Headers</h2>

        <table>

            <tr>

                <th>Header</th>

                <th>Status</th>

            </tr>

            {rows}

        </table>

        <p>

        <strong>Security Score:</strong>

        {headers['score']} / {headers['total']}

        ({percentage:.0f}%)

        </p>
        """

    # ------------------------------------------
    # HTML
    # ------------------------------------------

    html = f"""
<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<title>CyberScan Report</title>

<style>

body {{
    font-family: Arial, sans-serif;
    background: #f5f5f5;
    margin:40px;
}}

.container {{
    background:white;
    padding:30px;
    border-radius:10px;
    box-shadow:0 0 10px rgba(0,0,0,.1);
}}

h1 {{
    color:#0d6efd;
}}

table {{
    width:100%;
    border-collapse:collapse;
    margin-top:15px;
    margin-bottom:25px;
}}

th, td {{
    border:1px solid #ddd;
    padding:10px;
}}

th {{
    background:#0d6efd;
    color:white;
}}

</style>

</head>

<body>

<div class="container">

<h1>CyberScan Toolkit Report</h1>

<h2>Target Information</h2>

<table>

<tr>

<td>Target</td>

<td>{scan_result['target']}</td>

</tr>

<tr>

<td>IP Address</td>

<td>{scan_result['ip']}</td>

</tr>

</table>

<h2>Open Ports</h2>

<table>

<tr>

<th>Port</th>

<th>Service</th>

<th>Banner</th>

</tr>

{ports_rows}

</table>

{ssl_section}

{header_section}

<hr>

<p>

Generated by <strong>CyberScan Toolkit</strong>

</p>

</div>

</body>

</html>
"""

    with open(report_path, "w", encoding="utf-8") as file:

        file.write(html)

    return report_path